development:
  adapter: postgresql
  encoding: unicode
  database: web_dev
  pool: 5
  username: jmoscat
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: web_test
  pool: 5
  username: jmoscat
  password:
